package Exceptions;

public class LearnMainException {
	public static void main(String[] args) {
	//	int b = 0;
	//	if (b !=0) {
	//	try {		
	//	int value = 1/b;
	//	}
	//}catch(ArithmeticException e) {
	//	System.err.println(e);
	//	}
	//	System.out.println("end");
	//}
	/*int[] array = {};
	try {
	int value = array[0];
	}catch (ArrayIndexOutOfBoundsException e){
		System.err.println(e);
		}
	System.out.println("end");
	}*/
		Object ob = null;
		 
		ob.getClass();
	}
}
